name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/actionlint.yml'
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check workflow files
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
        with:
          version: 1.7.12
          pyflakes: false
